FROM ubuntu:18.04

RUN  apt-get update \
  && apt-get install -y \
  wget \
  libusb-1.0-0-dev \
  libusb-1.0-0 \
  libssl1.0.0

RUN wget http://builds.etcdevteam.com/emerald-cli/v0.22.x/emerald-cli-linux-v0.22.0+11-c210192.tar.gz && \
        tar -zxf emerald-cli-linux-v0.22.0+11-c210192.tar.gz && \
        ls && \
        cp target/release/emerald /usr/bin && \
        mv /usr/bin/emerald /usr/bin/emerald-vault

EXPOSE 1920

CMD emerald-vault server
